// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearHistory():Promise<boolean>;

export function DeleteFolderContents(arg1:Array<main.FolderEntry>,arg2:number):Promise<Array<main.DeleteResult>>;

export function GetFolderInfo(arg1:string):Promise<Record<string, any>>;

export function LoadHistory():Promise<Array<main.HistoryEntry>>;

export function SaveHistory(arg1:Array<main.HistoryEntry>):Promise<boolean>;

export function SelectFolder():Promise<string>;
