// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DeleteFolderContents(arg1, arg2) {
  return window['go']['main']['App']['DeleteFolderContents'](arg1, arg2);
}

export function GetFolderInfo(arg1) {
  return window['go']['main']['App']['GetFolderInfo'](arg1);
}

export function LoadHistory() {
  return window['go']['main']['App']['LoadHistory']();
}

export function SaveHistory(arg1) {
  return window['go']['main']['App']['SaveHistory'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}
